blueprint:
  name: "HmIP-BBL: Hybrid-Beschattung (Global Helpers)"
  description: >
    Steuert Homematic IP BBL Jalousien via Homematic(IP) Local.
    
    Features:
    - Kombinierter Befehl (Höhe & Lamelle) gegen Ruckeln.
    - Globale Grenzwerte über Input Number Helfer (skalierbar für viele Fenster).
    - Hybrid-Lichterkennung: Nutzt Lux-Sensor (auch im Schatten) + Wetterdaten.
    - Azimut-Steuerung pro Fenster.
  domain: automation
  source_url: https://gist.github.com/dein_user/dein_gist_id
  input:
    # --- INDIVIDUELLE GERÄTE ---
    cover_entity:
      name: Raffstore (HmIP-BBL)
      selector:
        entity:
          domain: cover
          integration: homematicip_local
    temp_sensor_in:
      name: Raumthermostat (Ist-Wert)
      selector:
        entity:
          domain: sensor
          device_class: temperature

    # --- FENSTER PARAMETER ---
    azimuth_start:
      name: Azimut Start (Grad)
      description: "Ab wann scheint die Sonne auf dieses Fenster?"
      default: 100
      selector:
        number:
          min: 0
          max: 360
    azimuth_end:
      name: Azimut Ende (Grad)
      description: "Wann verschwindet die Sonne wieder?"
      default: 260
      selector:
        number:
          min: 0
          max: 360

    # --- GLOBALE SENSOREN ---
    temp_sensor_out:
      name: Außentemperatur Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    wind_sensor:
      name: Windsensor (km/h)
      selector:
        entity:
          domain: sensor
          device_class: wind_speed
    illuminance_sensor:
      name: Helligkeitssensor (Lux)
      description: "Kann im Schatten liegen."
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    weather_entity:
      name: Wettervorhersage
      description: "Wird genutzt, wenn Lux-Sensor im Schatten ist."
      selector:
        entity:
          domain: weather
    sun_entity:
      name: Sonne
      default: sun.sun
      selector:
        entity:
          domain: sun

    # --- GLOBALE HELFER (INPUT NUMBERS) ---
    helper_temp_in_target:
      name: "Helfer: Zieltemperatur Innen"
      selector:
        entity:
          domain: input_number
    helper_temp_out_min:
      name: "Helfer: Min. Außentemperatur"
      selector:
        entity:
          domain: input_number
    helper_wind_limit:
      name: "Helfer: Wind Limit (km/h)"
      selector:
        entity:
          domain: input_number
    helper_lux_min:
      name: "Helfer: Lux Tagesschwelle (Schatten)"
      description: "Wert für 'Es ist Tag' im Schatten (z.B. 300)"
      selector:
        entity:
          domain: input_number
    helper_lux_spike:
      name: "Helfer: Lux Direktschwelle"
      description: "Wert bei direkter Sonne (Wetter egal)"
      selector:
        entity:
          domain: input_number
    
    # --- POSITIONEN ---
    # Optional auch als Helfer möglich, hier fest für Einfachheit, 
    # oder du erstellst Helfer dafür.
    shading_height:
      name: Beschattungshöhe (0-100%)
      default: 0
      selector:
        number:
          min: 0
          max: 100
    shading_tilt:
      name: Beschattungswinkel (0-100%)
      default: 50
      selector:
        number:
          min: 0
          max: 100

variables:
  cover_entity: !input cover_entity
  weather_ent: !input weather_entity
  lux_ent: !input illuminance_sensor
  
  # Mapping der Inputs auf Variablen
  h_temp_in: !input helper_temp_in_target
  h_temp_out: !input helper_temp_out_min
  h_wind: !input helper_wind_limit
  h_lux_min: !input helper_lux_min
  h_lux_spike: !input helper_lux_spike
  
  az_start: !input azimuth_start
  az_end: !input azimuth_end
  
  # Umrechnung Homematic
  pos_h: "{{ (inputs.shading_height | float) / 100.0 }}"
  pos_t: "{{ (inputs.shading_tilt | float) / 100.0 }}"

trigger:
  - platform: time_pattern
    minutes: "/5"
  # Trigger auf Wind (Sicherheit)
  - platform: numeric_state
    entity_id: !input wind_sensor
    above: !input helper_wind_limit
  # Trigger auf Raumtemperatur
  - platform: numeric_state
    entity_id: !input temp_sensor_in
    above: !input helper_temp_in_target

action:
  - choose:
      # 1. WINDSCHUTZ
      - conditions:
          - condition: numeric_state
            entity_id: !input wind_sensor
            above: !input helper_wind_limit
        sequence:
          - service: cover.open_cover
            target:
              entity_id: !input cover_entity
      
      # 2. NACHT
      - conditions:
          - condition: state
            entity_id: !input sun_entity
            state: "below_horizon"
        sequence:
          - service: homematicip_local.put_paramset
            data:
              device_id: "{{ device_id(cover_entity) }}"
              paramset_key: VALUES
              paramset:
                LEVEL: 0.0
                LEVEL_2: 0.0

      # 3. BESCHATTUNG (HYBRID)
      - conditions:
          - condition: state
            entity_id: !input sun_entity
            state: "above_horizon"
          
          # Azimut Check
          - condition: template
            value_template: >
              {% set az = state_attr(inputs.sun_entity, 'azimuth') | float(0) %}
              {{ az >= az_start and az <= az_end }}
          
          # Temp Checks (Helfer)
          - condition: numeric_state
            entity_id: !input temp_sensor_in
            above: !input helper_temp_in_target
          - condition: numeric_state
            entity_id: !input temp_sensor_out
            above: !input helper_temp_out_min
          
          # Lux/Wetter Hybrid Logic
          - condition: template
            value_template: >
              {% set min_l = states(h_lux_min)|float(300) %}
              {% set spike_l = states(h_lux_spike)|float(20000) %}
              {% set cur_l = states(lux_ent)|float(0) %}
              
              {% set is_day = cur_l > min_l %}
              {% set is_spike = cur_l > spike_l %}
              {% set weather_ok = states(weather_ent) in ['sunny', 'partlycloudy', 'clear-night'] %}
              
              {{ is_spike or (is_day and weather_ok) }}
        
        sequence:
          - if:
              - condition: template
                value_template: >
                  {{ state_attr(cover_entity, 'current_position')|int != inputs.shading_height 
                     or state_attr(cover_entity, 'current_tilt_position')|int != inputs.shading_tilt }}
            then:
              - service: homematicip_local.put_paramset
                data:
                  device_id: "{{ device_id(cover_entity) }}"
                  paramset_key: VALUES
                  paramset:
                    LEVEL: "{{ pos_h }}"
                    LEVEL_2: "{{ pos_t }}"

    # 4. DEFAULT (Hochfahren)
    default:
      - if:
          - condition: state
            entity_id: !input sun_entity
            state: "above_horizon"
          - condition: template
            value_template: "{{ state_attr(cover_entity, 'current_position') < 95 }}"
        then:
          - service: cover.open_cover
            target:
              entity_id: !input cover_entity