blueprint:
  name: "HmIP-BBL: Master V7 (0-50% Tilt Logic)"
  description: >
    Spezial-Version für Raffstores mit 0-50% Arbeitsbereich.
    0% = Geschlossen (Zu).
    50% = Waagerecht (Offen/Maximal).
    Werte >50% werden für Beschattung vermieden (Wendung).
    
    Features: Adaptive Hitzeschutz-Nachführung (0-50%), Hybrid-Lichterkennung,
    Wochentags-Logik, globale Helfer.
  domain: automation
  input:
    # --- GERÄTE ---
    cover_entity:
      name: Jalousie (HmIP-BBL)
      selector: { entity: { domain: cover, integration: homematicip_local } }
    temp_sensor_in:
      name: Raumthermostat
      selector: { entity: { domain: sensor, device_class: temperature } }

    # --- ADAPTIVE TILT (0-50% LOGIK) ---
    adaptive_tilt_mode:
      name: "Dynamische Lamellennachführung?"
      description: "Berechnet Winkel anhand Sonnenhöhe (Elevation)."
      default: true
      selector: { boolean: {} }
    adaptive_min_tilt:
      name: "Tilt bei tiefer Sonne (0° Elev)"
      description: "Sollte 0 sein (ganz zu)."
      default: 0
      selector: { number: { min: 0, max: 50 } }
    adaptive_max_tilt:
      name: "Tilt bei hoher Sonne (>60° Elev)"
      description: "Sollte 50 sein (waagerecht). Nicht höher gehen!"
      default: 50
      selector: { number: { min: 0, max: 50 } }
    
    # --- ZEITEN ---
    workday_sensor:
      name: Arbeitstag-Sensor
      default: binary_sensor.workday_sensor
      selector: { entity: { domain: binary_sensor } }
    time_earliest_workday:
      name: "Öffnen: Frühestens (Werktag)"
      default: "06:30:00"
      selector: { time: {} }
    time_earliest_weekend:
      name: "Öffnen: Frühestens (Wochenende)"
      default: "08:30:00"
      selector: { time: {} }
    time_latest_open:
      name: "Öffnen: Spätestens (Force Open)"
      default: "10:00:00"
      selector: { time: {} }
    time_earliest_close:
      name: "Schließen: Frühestens"
      default: "17:00:00"
      selector: { time: {} }
    time_latest_close:
      name: "Schließen: Spätestens"
      default: "22:30:00"
      selector: { time: {} }

    # --- FENSTER GEOMETRIE ---
    azimuth_start:
      name: Azimut Start
      default: 100
      selector: { number: { min: 0, max: 360 } }
    azimuth_end:
      name: Azimut Ende
      default: 260
      selector: { number: { min: 0, max: 360 } }

    # --- GLOBALE SENSOREN ---
    temp_sensor_out:
      name: Sensor Außentemperatur
      selector: { entity: { domain: sensor, device_class: temperature } }
    wind_sensor:
      name: Sensor Wind
      selector: { entity: { domain: sensor, device_class: wind_speed } }
    illuminance_sensor:
      name: Sensor Helligkeit (SenseBox)
      selector: { entity: { domain: sensor, device_class: illuminance } }
    weather_entity:
      name: Wettervorhersage
      selector: { entity: { domain: weather } }
    sun_entity:
      name: Sonne
      default: sun.sun
      selector: { entity: { domain: sun } }

    # --- HELFER (Global) ---
    helper_temp_in_target:
      name: "Helfer: Zieltemperatur Innen"
      selector: { entity: { domain: input_number } }
    helper_temp_out_min:
      name: "Helfer: Min. Außentemperatur"
      selector: { entity: { domain: input_number } }
    helper_wind_limit:
      name: "Helfer: Wind Limit"
      selector: { entity: { domain: input_number } }
    helper_lux_min:
      name: "Helfer: Lux Tagesschwelle"
      selector: { entity: { domain: input_number } }
    helper_lux_spike:
      name: "Helfer: Lux Direktschwelle"
      selector: { entity: { domain: input_number } }

    # --- STATIC FALLBACK ---
    shading_height:
      name: Beschattungshöhe (Static)
      description: "0 = Unten (Standard)."
      default: 0
      selector: { number: { min: 0, max: 100 } }
    shading_tilt_static:
      name: Beschattungswinkel (Static)
      description: "Nur genutzt, wenn Adaptive Mode AUS ist. Max 50!"
      default: 50
      selector: { number: { min: 0, max: 50 } }

variables:
  # ... VAR MAPPING ...
  cover_entity: !input cover_entity
  sun_ent: !input sun_entity
  use_adaptive: !input adaptive_tilt_mode
  
  # TILT BERECHNUNG (0-50 Range)
  t_min: !input adaptive_min_tilt
  t_max: !input adaptive_max_tilt
  elevation: "{{ state_attr(sun_ent, 'elevation') | float(0) }}"
  
  calc_tilt: >
    {% if use_adaptive %}
      {# Elevation 0-60 Grad auf Bereich t_min-t_max mappen #}
      {% set el_clamped = [0, [elevation, 60]|min]|max %}
      {% set factor = el_clamped / 60.0 %}
      {# Beispiel: Elev 30 -> Factor 0.5 -> 0 + 0.5 * (50-0) = 25% #}
      {% set dynamic = t_min + (factor * (t_max - t_min)) %}
      {{ dynamic | int }}
    {% else %}
      {{ inputs.shading_tilt_static | int }}
    {% endif %}

  # ... RESTLICHE VARS ...
  workday_ent: !input workday_sensor
  weather_ent: !input weather_entity
  lux_ent: !input illuminance_sensor
  h_temp_in: !input helper_temp_in_target
  h_temp_out: !input helper_temp_out_min
  h_wind: !input helper_wind_limit
  h_lux_min: !input helper_lux_min
  h_lux_spike: !input helper_lux_spike
  t_early_work: !input time_earliest_workday
  t_early_we: !input time_earliest_weekend
  t_latest_open: !input time_latest_open
  t_early_close: !input time_earliest_close
  t_latest_close: !input time_latest_close
  az_start: !input azimuth_start
  az_end: !input azimuth_end
  
  # Homematic 0.0 - 1.0 (Höhe) und 0.0 - 0.5 (Tilt für 0-50%)
  pos_h: "{{ (inputs.shading_height | float) / 100.0 }}"
  pos_t: "{{ (calc_tilt | float) / 100.0 }}"

trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: numeric_state
    entity_id: !input wind_sensor
    above: !input helper_wind_limit
  - platform: numeric_state
    entity_id: !input temp_sensor_in
    above: !input helper_temp_in_target

action:
  - choose:
      # 1. WINDSCHUTZ
      - conditions:
          - condition: numeric_state
            entity_id: !input wind_sensor
            above: !input helper_wind_limit
        sequence:
          - service: cover.open_cover
            target:
              entity_id: !input cover_entity
      
      # 2. SCHLIEßEN (INTELLIGENT)
      - conditions:
          - condition: template
            value_template: >
              {% set sun_down = is_state(sun_ent, 'below_horizon') %}
              {% set t_now = now().strftime('%H:%M:%S') %}
              {% set force_close = t_now >= t_latest_close %}
              {% set sunset_close = sun_down and (t_now >= t_early_close) %}
              {{ force_close or sunset_close }}
        sequence:
          - service: homematicip_local.put_paramset
            data:
              device_id: "{{ device_id(cover_entity) }}"
              paramset_key: VALUES
              paramset:
                LEVEL: 0.0
                LEVEL_2: 0.0 # Zu

      # 3. BESCHATTUNG (HYBRID + ADAPTIVE 0-50)
      - conditions:
          - condition: state
            entity_id: !input sun_entity
            state: "above_horizon"
          - condition: template
            value_template: >
              {% set az = state_attr(sun_ent, 'azimuth') | float(0) %}
              {{ az >= az_start and az <= az_end }}
          - condition: numeric_state
            entity_id: !input temp_sensor_in
            above: !input helper_temp_in_target
          - condition: numeric_state
            entity_id: !input temp_sensor_out
            above: !input helper_temp_out_min
          - condition: template
            value_template: >
              {% set min_l = states(h_lux_min)|float(300) %}
              {% set spike_l = states(h_lux_spike)|float(20000) %}
              {% set cur_l = states(lux_ent)|float(0) %}
              {% set is_day = cur_l > min_l %}
              {% set is_spike = cur_l > spike_l %}
              {% set weather_ok = states(weather_ent) in ['sunny', 'partlycloudy', 'clear-night'] %}
              {{ is_spike or (is_day and weather_ok) }}
        sequence:
          # Hysterese Prüfung (Ruckelschutz)
          - if:
              - condition: template
                value_template: >
                  {% set current_h = state_attr(cover_entity, 'current_position') | int %}
                  {% set current_t = state_attr(cover_entity, 'current_tilt_position') | int %}
                  {% set target_h = (inputs.shading_height | int) %}
                  {% set target_t = (calc_tilt | int) %}
                  
                  {# Nur fahren wenn Tilt um >3% abweicht (feinere Auflösung für 0-50 Bereich) #}
                  {% set tilt_diff = (current_t - target_t) | abs %}
                  {% set tilt_mismatch = tilt_diff > 3 %}
                  {% set height_mismatch = current_h != target_h %}
                  
                  {{ height_mismatch or tilt_mismatch }}
            then:
              - service: homematicip_local.put_paramset
                data:
                  device_id: "{{ device_id(cover_entity) }}"
                  paramset_key: VALUES
                  paramset:
                    LEVEL: "{{ pos_h }}"
                    LEVEL_2: "{{ pos_t }}"

    # 4. DEFAULT: ÖFFNEN
    default:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {% set is_work = states(workday_ent) == 'on' %}
                  {% set early_time = t_early_work if is_work else t_early_we %}
                  {% set t_now = now().strftime('%H:%M:%S') %}
                  {% set is_after_early = t_now >= early_time %}
                  {% set is_after_latest = t_now >= t_latest_open %}
                  {% set is_sun_up = is_state(sun_ent, 'above_horizon') %}
                  {{ (is_sun_up and is_after_early) or is_after_latest }}
              - condition: template
                value_template: "{{ state_attr(cover_entity, 'current_position') < 95 }}"
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: !input cover_entity